# WARNING: DO NOT COMMIT REAL PRODUCTION SECRETS TO GIT
# This is an example template for Kubernetes Secrets.
# In production, use AWS Secrets Manager, HashiCorp Vault, or SealedSecrets.
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devsecops
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb-service:27017/devsecops-db"
  DB_USERNAME: "admin"
  DB_PASSWORD: "change-me-in-production-vault"
